javers/javers

- javers-core/src/main/java/org/javers/common/reflection/ReflectionUtil.java
The function `isGetter()` checks if a method name begins with "get" or
"is". Previously, the code used `.substring(0,3)`, which throws an error
if the method name is fewer than 3 characters. `startswith()` won't
throw an error in that case and will instead return false.
> Use startswith() to determine if method is getter

- javers-core/src/main/java/org/javers/common/reflection/ReflectionUtil.java
- javers-core/src/test/groovy/org/javers/core/metamodel/type/CollectionTypeTest.groovy
If I try to use JaVers to compare classes with upper-bounded wildcard types, I get an exception with message like the following:
```
beaconJaversException: GENERIC_TYPE_NOT_PARAMETRIZED JaVers runtime error - 
expected actual Class argument in type 'java.util.Set<? extends Foo>'. 
JaVers is strongly-typed and needs to know actual Class of elements stored in your collections. 
```
with an instruction to:
```
Try at least <Object>. Wildcards (e.g. <?>), unbounded type parameters (e.g. <T>) and raw types (e.g. List) are not supported.
```
For reasons, we cannot easily alter our model to narrow to `Set<Foo>` or `Set<SpecificSubclassOfFoo>`, and anyway we would prefer not to let our choice of this (admittedly wonderful) tool drive such things.
The error actually does not say that bounded …
> For WildcardType, use Types of upper bounds (i.e. erase wildcard)

- javers-core/src/main/java/org/javers/core/AbstractJaversBuilder.java
Besides getComponents every other getter and adder in AbstractJavaBuilder class checks if container is already created.
> Small consistency fixes

- javers-core/src/main/java/org/javers/core/changelog/SimpleTextChangeLog.java
Pewnie najlepiej byłoby żeby przekazany dateTimeFormatter był wykorzystywany również do wypisywania zmian dotyczących dat. Natomiast ta wersja jest lepsza od stanu obecnego bo używa formattera przekazanego w konstruktorze przynajmniej do wypisania daty i czasu commita.
> Commit date formatting in SimpleTextChangelog

- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/H2SqlRepositoryE2ETest.groovy
After each test case connection to SQL database is closed.
DB_CLOSE_DELAY=-1 in database URL prevents inmemory H2 
database from closing (and losing all its content) after last
connection to database is closed.
It's important because of a way in which PolyJDBC handles primary
keys generation. PolyJDBC can generate more than one key from a 
single sequence value fetch. In consequence isolation between test 
cases is broken.
> Fix of H2 repository test environment

- javers-core/src/main/java/org/javers/core/graph/EdgeBuilder.java
- javers-core/src/main/java/org/javers/repository/api/SnapshotIdentifier.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/ManagedClassFilter.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/PrimaryKeySnapshotFilter.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/SnapshotFilter.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/VoOwnerEntityFilter.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2039 - Member variable visibility should be specified
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2039
Please let me know if you have any questions.
M-Ezzat
> squid:S2039 - Member variable visibility should be specified

- javers-core/src/main/java/org/javers/core/diff/changetype/PropertyChange.java
Sorry I haven't written a test, but I've not really done much Groovy and it's 20:58 on a Friday evening and I'm watching TV!
> fix bug that causes PropertyChange#equals to always return false

- javers-core/src/main/java/org/javers/core/diff/changetype/container/ContainerElementChange.java
- javers-core/src/main/java/org/javers/core/diff/changetype/container/ElementValueChange.java
- javers-core/src/main/java/org/javers/core/diff/changetype/container/ValueAddOrRemove.java
- javers-core/src/main/java/org/javers/core/diff/changetype/map/EntryAddOrRemove.java
- javers-core/src/main/java/org/javers/core/diff/changetype/map/EntryChange.java
- javers-core/src/main/java/org/javers/core/diff/changetype/map/EntryValueChange.java
- javers-core/src/test/groovy/org/javers/core/diff/changetype/container/ElementValueChangeTest.groovy
- javers-core/src/test/groovy/org/javers/core/diff/changetype/container/ValueAddedTest.groovy
- javers-core/src/test/groovy/org/javers/core/diff/changetype/container/ValueRemovedTest.groovy
- javers-core/src/test/groovy/org/javers/core/diff/changetype/map/EntryAddedTest.groovy
- javers-core/src/test/groovy/org/javers/core/diff/changetype/map/EntryRemovedTest.groovy
- javers-core/src/test/groovy/org/javers/core/diff/changetype/map/EntryValueChangeTest.groovy
I've added some more object equality implementations, as I was having difficulty testing that my usage of Javers was creating the expected changes. 
I hope the Spock tests are acceptable - not written any before, so I was just trying to copy the style that was elsewhere.
> Change Object Equality

- javers-core/src/main/java/org/javers/core/metamodel/type/TypeMapperState.java
Class loaded by different classLoader are not equal, so using Class as map key will have mare than one entry in that map. Use type name instead.
The failed test case could be reproduce when work with Spring-Boot 1.3+ and DevTools.
> Fix TypeMapperState.mappedTypes. 

- javers-core/src/main/java/org/javers/repository/jql/QueryBuilder.java
It seems the parameter `withNewObjectChanges `was missed to pass to `queryParamsBuilder`.
```
public QueryBuilder withNewObjectChanges(boolean newObjectChanges) {  // newObjectChanges not passed to queryParamsBuilder
queryParamsBuilder.newObjectChanges(true);
return this;
}
```
> Update QueryBuilder::withNewObjectChanges(boolean) method to use parameter

- javers-core/src/main/java/org/javers/core/json/JsonConverterBuilder.java
- javers-persistence-mongo/src/test/groovy/org/javers/repository/mongo/CrossReferenceTest.groovy
- javers-persistence-mongo/src/test/java/org/javers/repository/mongo/model/CrossReferenceHost.java
- javers-persistence-mongo/src/test/java/org/javers/repository/mongo/model/CrossReferenceObjectA.java
- javers-persistence-mongo/src/test/java/org/javers/repository/mongo/model/CrossReferenceObjectB.java
Set gsonBuilder exclusionStrategies to avoid nested ValueObject circular reference.
> Avoid nested DiffIgnored ValueObject being compare

- javers-core/src/main/java/org/javers/core/metamodel/annotation/IgnoreDeclaredProperties.java
- javers-core/src/main/java/org/javers/core/metamodel/scanner/BeanBasedPropertyScanner.java
- javers-core/src/main/java/org/javers/core/metamodel/scanner/FieldBasedPropertyScanner.java
- javers-core/src/main/java/org/javers/core/metamodel/type/ManagedClassFactory.java
- javers-core/src/test/groovy/org/javers/core/JaversDiffE2ETest.groovy
- javers-core/src/test/groovy/org/javers/core/metamodel/scanner/PropertyScannerTest.groovy
- javers-core/src/test/groovy/org/javers/core/model/DummyIgnoredPropertiesType.groovy
Add @IgnoreDeclaredProperties to classes to ignore all their properties.
If a class is annotated with @IgnoreDeclaredProperties and is part of an audited hierarchy, only the properties of the class are ignored, and JaVers will still track any other properties in the class hierarchy.
By contrast, if a class is annotated with @DiffIgnore JaVers will ignore all instances of that class.
> 448 Add @IgnoreDeclaredProperties annotation

- javers-core/src/main/java/org/javers/common/reflection/JaversMethodFactory.java
- javers-core/src/test/groovy/org/javers/core/metamodel/type/TypeFactoryBeanIdTest.groovy
- javers-core/src/test/java/org/javers/core/model/AbstractEntity.java
- javers-core/src/test/java/org/javers/core/model/Entity.java
The proposed solution is to ignore bridge methods in the method JaversMethodFactory.getAllMethods().
Two test models and 1 test to test this particular scenario has been added.
> fix type erasure issue with Bean MappingStyle

- javers-core/src/test/groovy/org/javers/core/json/JsonConverterUtilTypesTest.groovy
Test for file path serialization assumed execution
in UNIX environment and because of that was failing
in Windows
> fixing path serilization test

- javers-persistence-sql/build.gradle
- javers-persistence-sql/src/main/java/org/javers/repository/sql/JaversSqlRepository.java
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/H2SqlRepositoryE2ETest.groovy
- javers-spring-boot-starter-sql/src/main/java/org/javers/spring/boot/sql/JaversSqlAutoConfiguration.java
Changes:
- PolyJDBC upgrated to 0.6.6
- Exposed JaversSqlRepository as an Spring Bean
With the new method in JaversRepository, `JaversSqlRepository.evictCache()` can be misleading. I am wondering if we can rename it to something like `JaversSqlRepository.evictGlobalIdCache()`.
> #532 possibility to clear SequenceAllocation cache

- javers-persistence-sql/build.gradle
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/JaversSchemaManager.java
- Adding alter statement for mysql test text -> varchar(max) conversion.
- Setting gradle to pull new version of polyjdbc
- Adding mssql driver for testing  (unsure if this should be committed but I couldn't test without it, intellij was saying that I needed a driver.)
Note: I ran the tests with the build and the mssql integration tests and everything came up green 😄
> Javers uses deprecated type TEXT for mssql for Snapshot_State and Snapshot_Changed fields

- javers-core/src/main/java/org/javers/core/diff/ListCompareAlgorithm.java
- javers-core/src/main/java/org/javers/core/diff/appenders/SetChangeAppender.java
- javers-core/src/main/java/org/javers/core/diff/appenders/SetListChangeAppender.java
- javers-core/src/main/java/org/javers/core/metamodel/type/TypeMapper.java
- javers-core/src/test/groovy/org/javers/core/diff/appenders/AbstractDiffAppendersTest.groovy
- javers-core/src/test/groovy/org/javers/core/diff/appenders/SetAppenderTest.groovy
- javers-core/src/test/groovy/org/javers/core/diff/appenders/SetChangeAppenderTest.groovy
- javers-core/src/test/groovy/org/javers/core/diff/appenders/SetListChangeAppenderTest.groovy
- javers-core/src/test/groovy/org/javers/core/model/DummyUser.groovy
Add new compare Algorithm to be able compare lists like a sets (ignoring ordering).
For now, If we want to compare collection without ordering, we should to use sets.
In case, when we need to ignore ordering and we can not to change existing lists Objects to sets we have some troubles. 
We can not to change our model and use Sets.
> #605 Add List compare Algorithm SET.

- javers-core/src/main/java/org/javers/core/metamodel/type/EntityType.java
- javers-core/src/test/groovy/org/javers/core/JaversDiffE2ETest.groovy
When I try to use an Entity as Id of another Entity I got "java.lang.ClassCastException: org.javers.core.metamodel.type.EntityType cannot be cast to org.javers.core.metamodel.type.PrimitiveOrValueType"
The alteration that I need is relatively simple to make Javers accept this condition.
> Adding support for Entity Type as Id of another Entity

- javers-core/src/main/java/org/javers/common/date/DateProvider.java
- javers-core/src/main/java/org/javers/common/date/DefaultDateProvider.java
- javers-core/src/main/java/org/javers/core/CommitIdGenerator.java
- javers-core/src/main/java/org/javers/core/commit/Commit.java
- javers-core/src/main/java/org/javers/core/commit/CommitFactory.java
- javers-core/src/main/java/org/javers/core/commit/CommitMetadata.java
- javers-core/src/main/java/org/javers/core/json/CdoSnapshotSerialized.java
- javers-core/src/main/java/org/javers/core/json/typeadapter/commit/CdoSnapshotAssembler.java
- javers-core/src/main/java/org/javers/core/json/typeadapter/commit/CommitMetadataTypeAdapter.java
- javers-core/src/main/java/org/javers/core/json/typeadapter/util/UtilTypeCoreAdapters.java
- javers-core/src/test/groovy/org/javers/core/FakeDateProvider.groovy
- javers-core/src/test/groovy/org/javers/core/JaversCommitE2ETest.groovy
- javers-core/src/test/groovy/org/javers/core/JaversRepositoryE2ETest.groovy
- javers-core/src/test/groovy/org/javers/core/JaversTestBuilder.groovy
- javers-core/src/test/groovy/org/javers/core/TikDateProvider.groovy
- javers-core/src/test/groovy/org/javers/core/commit/CommitMetadataTest.groovy
- javers-core/src/test/groovy/org/javers/core/examples/JqlExample.groovy
- javers-core/src/test/groovy/org/javers/core/json/JsonConverterDateTimeTest.groovy
- javers-core/src/test/groovy/org/javers/core/json/typeadapter/CdoSnapshotTypeAdapterTest.groovy
- javers-core/src/test/groovy/org/javers/core/snapshot/ChangedCdoSnapshotsFactoryTest.groovy
- javers-core/src/test/groovy/org/javers/core/snapshot/SnapshotFactoryTest.groovy
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepository.java
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoSchemaManager.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/JaversSqlRepository.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/SnapshotQuery.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/repositories/CommitMetadataRepository.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/FixedSchemaFactory.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/JaversSchemaManager.java
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/JaversSqlRepositoryE2ETest.groovy
`Instant commitDateInstant` is added to `CommitMetadata` in order to provide
reliable chronological ordering when applications nodes works in more than one time zone.
> Commit.commitDateInstant

- javers-core/src/main/java/org/javers/core/metamodel/object/GlobalId.java
- javers-core/src/test/java/org/javers/core/cases/Case779SortedSets.java
- javers-core/src/test/java/org/javers/core/cases/CaseXXXSortedSets.java
Client domain object snapshots are unable to deserialize, due the fact that GlobalId instances are not `Comparable`.
> Sorted set bug test case

- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoSchemaManager.java
Index name has been added. I only explicitly set the name of the one compound index that resulted in a very long generated name in mongo. Let me know if I should set all of them. Also, I tested that this does not cause issues on Mongo DB instances where the schema was already initialized with the old index name; the existing index is not replaced and no error is thrown by the Mongo driver. This was tested on Mongo 3.6.2.
> #788 Explicitly set name for MongoDB snapshot commit property index

- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepository.java
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoSchemaManager.java
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoAutoConfiguration.java
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoProperties.java
I took a crack at adding DocumentDB compatibility to the existing MongoRepository. The only functional difference is creation of the commit metadata property index. Let me know if you would prefer supporting this in another way, such as with a seperate JaversRepository implementation.
Thanks!
> Amazon DocumentDB compatibility implementation.

- javers-core/src/main/java/org/javers/common/collections/Sets.java
- javers-core/src/test/groovy/org/javers/core/cases/Case815CommitEmptyValueObject.groovy
See #815 
Includes the simple fix for this issue along with a Groovy test case.
> 815: UnsupportedOperationException committing empty ValueObject when previous version was not empty

- javers-core/src/main/java/org/javers/common/string/ToStringBuilder.java
toString always shows discouraging "Field Map<String, String>..." instead of correct "Field Map<String, MyClass>..."
> fix toString() bug

- gradle.properties
Fixes building on windows. 
(Upgrade to 2.1.2 also fixes the error, but I decided to choose the highest.)
Original error with embedded mongo 2.1.1:
```
22:33:45.889 [main] ERROR d.f.e.p.runtime.AbstractProcess - failed to call onAfterProcessStart()
java.io.IOException: Could not start process: <EOF>
at de.flapdoodle.embed.mongo.AbstractMongoProcess.onAfterProcessStart(AbstractMongoProcess.java:79) [de.flapdoodle.embed.mongo-2.1.1.jar:na]
at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:116) ~[de.flapdoodle.embed.process-2.0.5.jar:na]
at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53) [de.flapdoodle.embed.mongo-2.1.1.jar:na]
at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50) …
```
> Upgrade embedded mongo to 2.2.0

- javers-core/src/main/java/org/javers/core/metamodel/type/ListType.java
- javers-core/src/main/java/org/javers/core/metamodel/type/MapType.java
- javers-core/src/main/java/org/javers/core/metamodel/type/SetType.java
- javers-core/src/main/java/org/javers/guava/MultimapType.java
- javers-core/src/main/java/org/javers/guava/MultisetType.java
- javers-core/src/test/groovy/org/javers/core/cases/CaseWithSortedCollectionPropertyType.groovy
Fixed the regression in generating changes when property types are sub-types of base enumerable types (e.g., SortedMap, SortedSet, etc.)
> https://github.com/javers/javers/issues/888

- javers-core/src/main/java/org/javers/core/CommitIdGenerator.java
- javers-core/src/test/groovy/org/javers/core/CommitIdGeneratorTest.groovy
Provides some level of security over duplicated commits when comparing shadows
Without this additional criteria, shadows with the same commit id will get the commit metadata from the earliest commit, rather than the commit associated to the shadow object
https://github.com/javers/javers/issues/894
> Update comparator for Synchronized Sequence to be safer with distributed systems

- javers-core/src/main/java/org/javers/common/exception/JaversExceptionCode.java
- javers-core/src/main/java/org/javers/core/commit/DistributedCommitSeqGenerator.java
- javers-core/src/test/groovy/org/javers/core/JaversRepositoryE2ETest.groovy
- javers-persistence-sql/build.gradle
- javers-persistence-sql/src/main/java/org/javers/repository/sql/repositories/CommitMetadataRepository.java
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/H2SqlRepositoryE2ETest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/H2SqlRepositoryE2EWithSchemaTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/JaversSqlRepositoryE2ETest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/docker/MySqlDockerIntegrationTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/opendatabases/MySqlIntegrationTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/opendatabases/MySqlIntegrationWithSchemaTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/opendatabases/PostgreSqlIntegrationTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/opendatabases/PostgreSqlIntegrationWithSchemaTest.groovy
better test for concurrent writes from many Javers instances to the same DB
> removed throwing of CANT_SAVE_ALREADY_PERSISTED_COMMIT exception

- javers-core/src/main/java/org/javers/core/json/JsonConverterBuilder.java
- javers-core/src/test/groovy/org/javers/core/cases/CaseWithBuiltInTypeAdaptersOverride.groovy
I am new to the open source world and this is the first time I'm writing any groovy. Please attribute any mistakes to ignorance rather than malice
> Test Cases For Custom Date Serialization

- javers-persistence-mongo/src/test/groovy/org/javers/repository/mongo/EmbeddedMongoE2ETest.groovy
- javers-persistence-mongo/src/test/groovy/org/javers/repository/mongo/EmbeddedMongoFactory.groovy
- javers-persistence-mongo/src/test/groovy/org/javers/repository/mongo/NewMongoPerformanceTest.groovy
- javers-persistence-mongo/src/test/groovy/org/javers/repository/mongo/cases/CrossReferenceTest.groovy
- javers-persistence-mongo/src/test/groovy/org/javers/repository/mongo/cases/MapKeyDotReplacerTest.groovy
- javers-persistence-mongo/src/test/groovy/org/javers/repository/mongo/integration/MongoIntegrationTest.groovy
- javers-spring-boot-starter-mongo/README.md
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversDedicatedMongoFactory.java
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoAutoConfiguration.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterDedicatedMongoTest.groovy
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterDefaultsTest.groovy
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/config/MongoClientConfig.java
- javers-spring-boot-starter-mongo/src/test/java/org/javers/spring/boot/mongo/config/MongoClientConfig.java
- javers-spring/src/test/groovy/org/javers/spring/auditable/integration/EmbeddedMongoFactory.groovy
- javers-spring/src/test/groovy/org/javers/spring/auditable/integration/TestApplicationConfig.groovy
- javers-spring/src/test/java/org/javers/spring/example/JaversSpringMongoApplicationConfig.java
- Replaced all the imports of `MongoClient` from `com.mongodb.MongoClient` to `com.mongodb.client.MongoClient`
- Using `MongoClients` from `com.mongodb.client` package to construct `MongoClient` which is now the recommended way.
> #962 Replace references to legacy MongoClient with newer version.

- javers-spring/src/main/java/org/javers/spring/auditable/aspect/springdata/JaversSpringDataAuditableRepositoryAspect.java
Adding @order(0) to JaversSpringDataAuditableRepositoryAspect.
Why ?
This aspect contains advices that run for all save/delete operations in
the application but since there is no order present with it. It takes
the default order which is highest precedence as it is using after-
advices. So giving it order 0 would help if some other advice needed to
execute before this.
That's why explicitly giving it 0.
> #981 Adding @Order(0) to JaversSpringDataAuditableRepositoryAspect.

- javers-core/src/main/java/org/javers/core/metamodel/type/InstanceIdFactory.java
- javers-core/src/test/groovy/org/javers/core/examples/CompositeIdExample.groovy
When using the IdClass annotation and using the Entities as the Id property javers should only reference the inner id fields instead of using the toString on the object.
With the dehydrate it will only store the Id property of the referenced entity in the InstanceId.
Referenced from: #1077
> Handle Composite id with IdClass annotation

- javers-core/src/main/java/org/javers/core/commit/CommitFactory.java
- javers-core/src/main/java/org/javers/core/snapshot/SnapshotFactory.java
- javers-core/src/test/groovy/org/javers/core/JaversCommitE2ETest.groovy
- javers-core/src/test/groovy/org/javers/core/snapshot/SnapshotFactoryTest.groovy
When trying to delete an inexistent object from a repository instead of
throwing an exception, create a terminal commit for the given object, as
version 1.
> Fixes #1108: Allow deleting inexistent object from repository.

- javers-core/src/main/java/org/javers/core/commit/CommitFactory.java
- javers-core/src/main/java/org/javers/core/snapshot/SnapshotFactory.java
- javers-core/src/test/groovy/org/javers/core/JaversCommitE2ETest.groovy
- javers-core/src/test/groovy/org/javers/core/snapshot/SnapshotFactoryTest.groovy
When trying to delete an inexistent object from a repository instead of
throwing an exception, create a terminal commit for the given object, as
version 1.
> #1108: Allow deleting inexistent object from repository.

- javers-core/src/test/groovy/org/javers/core/cases/Case1157SetOfSet.groovy
On my machine this test fails with the following output:
```
...
detectedDiffs == 0
|             |
48            false
...
```
The number of detected diffs is changing with each test invocation.
> #1157 Comparing Set of Set is non-deterministic

- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoAutoConfiguration.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterIntegrationTest.groovy
- javers-spring-boot-starter-mongo/src/test/java/org/javers/spring/boot/mongo/TestApplication.java
- javers-spring-boot-starter-sql/src/main/java/org/javers/spring/boot/sql/JaversSqlAutoConfiguration.java
- javers-spring-boot-starter-sql/src/test/groovy/org/javers/spring/sql/JaversSqlStarterIntegrationTest.groovy
- javers-spring-boot-starter-sql/src/test/java/org/javers/spring/boot/TestApplication.java
https://github.com/javers/javers/issues/1176
> #1176 Allow Javers customization from Spring Context

- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/FixedSchemaFactory.java
Use of gson.internal.LinkedHashTreeMap would prevent updating to gson 2.9.0
This PR fixes #1188
> Use HashMap instead of LinkedHashTreeMap

- javers-core/src/main/java/org/javers/core/CoreConfiguration.java
- javers-core/src/main/java/org/javers/core/CoreConfigurationBuilder.java
- javers-core/src/main/java/org/javers/core/JaversBuilder.java
- javers-core/src/main/java/org/javers/core/diff/DiffFactory.java
- javers-core/src/main/java/org/javers/core/graph/FakeNode.java
- javers-core/src/test/groovy/org/javers/core/nestedobjects/Item.java
- javers-core/src/test/groovy/org/javers/core/nestedobjects/ItemParent.java
- javers-core/src/test/groovy/org/javers/core/nestedobjects/NestedObjectTest.groovy
When having two objects of which one has a child object, JaVers is not able to recognize the difference,
when the properties of the child object have the same values as the corresponding default value in
org.javers.common.collections.Defaults
The first test ends successful, because the child Item has the value property `1`, which differs from the default
in Defaults (0).
The second test fails, because the child Item has the value property `0`, which is the same as the default in
Defaults (0).
In both tests the itemParentA, which has a child Item is compared to the itemParentB, which has no child Item.
Please ensure, that removed nested objects are removed properly. I think the Problem is the FakeNode which uses the
defaults from Defaults in the methods getDehydratedPropertyValue and …
> Bug when comparing nested objects

- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/Dialects.java
This reproduces the bug in #1168 by updating H2 to 2.1.210 which is good any was as earlier versions have known exploits https://mvnrepository.com/artifact/com.h2database/h2.
As recommended in H2 migration to v2 docs http://www.h2database.com/html/migration-to-v2.html this switches to sequence value expression https://h2database.com/html/grammar.html#sequence_value_expression
This is backwards compatible with H2 v1
> Fix #1168 Incorrect sequence SQL for H2 v2

- javers-spring-boot-starter-sql/src/main/java/org/javers/spring/boot/sql/DialectMapper.java
Oracle8iDialect and PostgreSQL81Dialect are deprecated in hibernate 6 and the instanceOf does not longer work for this dialects
> fix deprecations for postgres and hibernate dialect

- javers-core/src/main/java/org/javers/core/json/JsonConverterBuilder.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterNullDoubleTest.groovy
- javers-spring-boot-starter-mongo/src/test/java/org/javers/spring/boot/mongo/DummyEntityWithDouble.java
This PR resolves the issue found here: #1415
The previously failing test case now correctly persists the object containing Double.NaN.
> Fixing Issue #1415 with Double.NaN

- javers-core/src/main/java/org/javers/core/JaversBuilder.java
- javers-core/src/main/java/org/javers/core/commit/Commit.java
- javers-core/src/main/java/org/javers/core/commit/CommitFactory.java
- javers-core/src/main/java/org/javers/core/diff/DiffFactory.java
- javers-core/src/main/java/org/javers/core/diff/GraphPair.java
- javers-core/src/main/java/org/javers/core/diff/NodeMatcher.java
- javers-core/src/main/java/org/javers/core/metamodel/object/CdoSnapshot.java
- javers-core/src/main/java/org/javers/core/snapshot/ChangedCdoSnapshotsFactory.java
- javers-core/src/main/java/org/javers/core/snapshot/SnapshotDiffer.java
- javers-core/src/main/java/org/javers/core/snapshot/SnapshotGraphFactory.java
- javers-core/src/main/java/org/javers/repository/jql/ShadowQueryRunner.java
- javers-core/src/test/groovy/org/javers/core/JaversCommitE2ETest.groovy
- javers-core/src/test/groovy/org/javers/core/JaversDiffE2ETest.groovy
- javers-core/src/test/groovy/org/javers/core/JaversRepositoryE2ETest.groovy
- javers-core/src/test/groovy/org/javers/core/diff/NodeMatcherTest.groovy
- javers-core/src/test/groovy/org/javers/core/examples/JqlExample.groovy
- javers-core/src/test/groovy/org/javers/core/snapshot/SnapshotGraphFactoryTest.groovy
Fix for https://github.com/javers/javers/issues/1372
Value changes for removed Value Objects are now recorded in the queryForChanges
>  introduced terminal snapshots for removed Value Objects
