javers/javers

- javers-core/src/main/java/org/javers/core/metamodel/type/ParametrizedDehydratedType.java
- javers-core/src/test/groovy/org/javers/core/JaversRepositoryE2ETest.groovy
- javers-core/src/test/groovy/org/javers/core/metamodel/type/MapTypeTest.groovy
- javers-core/src/test/groovy/org/javers/core/metamodel/type/TypeMapperTest.groovy
- javers-core/src/test/java/org/javers/core/model/SnapshotEntity.java
> Fixed deserialization of objects of a generic type with generic arguments

- javers-core/build.gradle
- javers-core/src/main/java/org/javers/core/commit/Commit.java
- javers-core/src/main/java/org/javers/core/commit/CommitId.java
- javers-core/src/main/java/org/javers/core/metamodel/type/TypeFactory.java
- javers-core/src/main/java/org/javers/core/metamodel/type/TypeMapper.java
- javers-core/src/test/groovy/org/javers/core/metamodel/type/TypeMapperAsyncTest.groovy
fixed redundant JaversType spawning in TypeMapper
> https://github.com/javers/javers/issues/218

- javers-core/src/main/java/org/javers/common/collections/Lists.java
- javers-core/src/main/java/org/javers/core/diff/appenders/levenshtein/LevenshteinListChangeAppender.java
- javers-core/src/test/groovy/org/javers/core/diff/appenders/levenshtein/LevenshteinListChangeAppenderTest.groovy
> https://github.com/javers/javers/issues/240

- javers-persistence-sql/src/main/java/org/javers/repository/sql/ConnectionProvider.java
- javers-spring-boot-starter-sql/build.gradle
- javers-spring-boot-starter-sql/src/main/java/org/javers/spring/boot/sql/JaversProperties.java
- javers-spring-boot-starter-sql/src/main/java/org/javers/spring/boot/sql/JaversSqlAutoConfiguration.java
- javers-spring-boot-starter-sql/src/test/groovy/org/javers/spring/sql/JaversSqlAutoConfigurationTest.groovy
- javers-spring-boot-starter-sql/src/test/groovy/org/javers/spring/sql/JaversSqlIntegrationTest.groovy
- javers-spring-boot-starter-sql/src/test/java/org/javers/spring/boot/sql/DummyEntity.java
- javers-spring-boot-starter-sql/src/test/java/org/javers/spring/boot/sql/TestApplication.java
- javers-spring-boot-starter-sql/src/test/resources/application-integrationTest.yml
- javers-spring-boot-starter-sql/src/test/resources/application-test.yml
- settings.gradle
Daje do fixów z mongo bo z tego branch odbijałem
A co do tego PR, jest trochę cmd+c cmd+v :( np. JaversProperties, czy testy, nie wiem czy warto jest w tej chwili wyciągać trzeci moduł core - nie jestem do tego przekonany zostawiam do przemyślenia
> 204 spring boot starter jpa

- javers-core/src/main/java/org/javers/core/diff/appenders/ReferenceChangeAppender.java
- javers-core/src/main/java/org/javers/core/diff/changetype/ReferenceChange.java
- javers-core/src/test/groovy/org/javers/core/diff/appenders/OptionalChangeAppenderTest.groovy
- javers-core/src/test/groovy/org/javers/core/diff/appenders/ReferenceChangeAppenderTest.groovy
- javers-core/src/test/groovy/org/javers/core/diff/appenders/ReferenceChangeAssert.groovy
Any comments or feedback welcomed :)
> Issue 286 - expose object references in ReferenceChange

- javers-core/src/main/java/org/javers/common/exception/JaversExceptionCode.java
- javers-core/src/main/java/org/javers/common/reflection/JaversField.java
- javers-core/src/main/java/org/javers/core/diff/appenders/CollectionChangeFakeAppender.java
- javers-core/src/main/java/org/javers/core/diff/appenders/DiffAppendersModule.java
- javers-core/src/main/java/org/javers/core/metamodel/type/CollectionType.java
- javers-core/src/main/java/org/javers/core/metamodel/type/TypeMapper.java
- javers-core/src/main/java/org/javers/core/metamodel/type/TypeMapperState.java
- javers-core/src/test/groovy/org/javers/core/cases/CollectionPropertyErrorMessage.groovy
- javers-core/src/test/groovy/org/javers/core/metamodel/type/TypeMapperTest.groovy
handling raw collections properties
> https://github.com/javers/javers/issues/353

- javers-core/src/main/java/org/javers/core/diff/changetype/Atomic.java
- javers-core/src/main/java/org/javers/core/graph/ObjectNode.java
- javers-core/src/main/java/org/javers/core/metamodel/object/Cdo.java
- javers-core/src/main/java/org/javers/core/metamodel/object/CdoSnapshotState.java
- javers-core/src/main/java/org/javers/core/metamodel/object/GlobalId.java
- javers-core/src/main/java/org/javers/core/metamodel/type/EntityType.java
- javers-core/src/main/java/org/javers/core/metamodel/type/JaversType.java
This pull request is focused on resolving occurrences of Sonar rule pmd:SimplifyConditional - Simplify Conditional
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:SimplifyConditional
Please let me know if you have any questions.
M-Ezzat
> pmd:SimplifyConditional - Simplify Conditional

- javers-persistence-sql/build.gradle
- javers-persistence-sql/src/main/java/org/javers/repository/sql/SqlRepositoryBuilder.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/AnySnapshotFilter.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/CdoSnapshotFinder.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/CommitPropertyFinder.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/GlobalIdFilter.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/ManagedClassFilter.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/SnapshotFilter.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/SnapshotIdFilter.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/SnapshotIdentifiersFilter.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/VoOwnerEntityFilter.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/pico/JaversSqlModule.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/pico/TableNameManager.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/repositories/CdoSnapshotRepository.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/repositories/CommitMetadataRepository.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/repositories/GlobalIdRepository.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/FixedSchemaFactory.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/JaversSchemaManager.java
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/H2SqlRepositoryE2EWithSchemaTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/JaversSqlRepositoryE2ETest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/mssql/MsSqlIntegrationWithSchemaTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/opendatabases/MySqlIntegrationTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/opendatabases/MySqlIntegrationWithSchemaTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/opendatabases/PostgreSqlIntegrationWithSchemaTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/oracle/OracleIntegrationWithSchemaTest.groovy
Updated PolyJDBC library to have polyjdbc schema support
Added method in SqlRepositoryBuilder .withSchema() to be able to define a schema
Created TableNameManager to cater for table names which is used throughout the system.
> Added Schema support

- javers-core/src/main/java/org/javers/core/CommitIdGenerator.java
- javers-core/src/main/java/org/javers/core/JaversBuilder.java
- javers-core/src/main/java/org/javers/core/JaversCoreConfiguration.java
- javers-core/src/main/java/org/javers/core/commit/CommitFactory.java
- javers-core/src/main/java/org/javers/core/commit/CommitFactoryModule.java
- javers-core/src/main/java/org/javers/core/commit/CommitId.java
- javers-core/src/main/java/org/javers/core/commit/CommitIdFactory.java
- javers-core/src/main/java/org/javers/core/commit/CommitSeqGenerator.java
- javers-core/src/main/java/org/javers/core/commit/DistributedCommitSeqGenerator.java
- javers-core/src/test/groovy/org/javers/core/JaversRepositoryE2ETest.groovy
- javers-persistence-mongo/build.gradle
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/FixedSchemaFactory.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/JaversSchemaManager.java
> https://github.com/javers/javers/issues/411

- javers-persistence-sql/src/main/java/org/javers/repository/sql/JaversSqlRepository.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/SqlRepositoryBuilder.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/SqlRepositoryConfiguration.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/repositories/GlobalIdRepository.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/DBObjectName.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/TableNameProvider.java
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/H2SqlRepositoryE2ETest.groovy
- javers-spring/src/main/java/org/javers/spring/jpa/JaversTransactionalDecorator.java
- javers-spring/src/test/groovy/org/javers/spring/jpa/CacheEvictSpringConfig.groovy
- javers-spring/src/test/groovy/org/javers/spring/jpa/CacheEvictTest.groovy
- javers-spring/src/test/groovy/org/javers/spring/jpa/ErrorThrowingService.groovy
- javers-spring/src/test/java/org/javers/hibernate/integration/config/HibernateConfig.java
disable cache switch, evict cache method
> https://github.com/javers/javers/issues/467

- javers-core/src/main/java/org/javers/common/exception/JaversExceptionCode.java
- javers-spring-boot-starter-sql/src/main/java/org/javers/spring/boot/sql/JaversSqlAutoConfiguration.java
- javers-spring/src/main/java/org/javers/spring/jpa/JaversTransactionalDecorator.java
- javers-spring/src/main/java/org/javers/spring/jpa/TransactionalJaversBuilder.java
- javers-spring/src/test/groovy/org/javers/spring/jpa/CacheEvictSpringConfig.groovy
- javers-spring/src/test/groovy/org/javers/spring/jpa/ErrorThrowingService.groovy
- javers-spring/src/test/groovy/org/javers/spring/jpa/MultipleTxManagersConfig.groovy
- javers-spring/src/test/groovy/org/javers/spring/jpa/MultipleTxManagersTest.groovy
- javers-spring/src/test/java/org/javers/hibernate/integration/config/JaversBeanHibernateProxyConfig.java
- javers-spring/src/test/java/org/javers/hibernate/integration/config/JaversFieldHibernateProxyConfig.java
- javers-spring/src/test/java/org/javers/spring/boot/JaversSpringBootConfig.java
- javers-spring/src/test/java/org/javers/spring/example/JaversSpringJpaApplicationConfig.java
support for multiple transaction managers
> multiple txManagers

- javers-persistence-sql/build.gradle
https://github.com/javers/javers/issues/475
> polyjdbc fix in seq generator

- javers-core/src/main/java/org/javers/common/collections/WellKnownValueTypes.java
- javers-core/src/test/groovy/org/javers/core/json/JsonConverterWellKnownValuesTest.groovy
Pull request to fix issues with BigInteger as an @Id on entity
> 507 - BigInteger as ID for entityType causes INITIAL state to never exit

- javers-core/src/main/java/org/javers/core/metamodel/annotation/PropertyName.java
- javers-core/src/main/java/org/javers/core/metamodel/property/Property.java
- javers-core/src/main/java/org/javers/core/metamodel/scanner/AnnotationNamesProvider.java
- javers-core/src/main/java/org/javers/core/metamodel/scanner/AnnotationsNameSpace.java
- javers-core/src/main/java/org/javers/core/metamodel/scanner/BeanBasedPropertyScanner.java
- javers-core/src/main/java/org/javers/core/metamodel/scanner/FieldBasedPropertyScanner.java
- javers-core/src/main/java/org/javers/core/metamodel/scanner/JPAAnnotationsNameSpace.java
- javers-core/src/main/java/org/javers/core/metamodel/scanner/JaversAnnotationsNamesSpace.java
- javers-core/src/test/groovy/org/javers/core/metamodel/scanner/BeanBasedScannerTest.groovy
- javers-core/src/test/groovy/org/javers/core/metamodel/scanner/FieldBasedScannerTest.groovy
- javers-core/src/test/groovy/org/javers/core/model/DummyUserDetails.groovy
> #403 Support for PropertyName annotation has been implemented.

- build.gradle
- javers-core/src/main/java/org/javers/core/json/JsonConverter.java
> Add new method to JsonConverter - convert Reader to <T> Object

- gradle.properties
> Update Spring version

- gradle.properties
- javers-persistence-sql/src/main/java/org/javers/repository/sql/DialectName.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/FixedSchemaFactory.java
- javers-spring-boot-starter-sql/src/main/java/org/javers/spring/boot/sql/DialectMapper.java
https://github.com/polyjdbc/polyjdbc/pull/36
> Support for DB2 and DB2400

- javers-core/src/main/java/org/javers/core/metamodel/type/TypeMapperState.java
Changed class TypeMapperState to use `Logger` for debug prints.
> Debug print fix.

- javers-core/src/main/java/org/javers/core/graph/NodeReuser.java
- javers-core/src/test/groovy/org/javers/core/graph/ObjectGraphBuilderTest.groovy
> https://github.com/javers/javers/issues/543

- javers-spring-jpa/src/main/java/org/javers/spring/auditable/aspect/springdatajpa/JaversSpringDataJpaAuditableRepositoryAspect.java
Fixing my previous pull request. Noticed it just now.
> fix onDeleteInBatchExecuted() in JaversSpringDataJpaAuditableRepositoryAspect

- javers-core/src/main/java/org/javers/core/Changes.java
- javers-spring-jpa/src/test/java/org/javers/hibernate/integration/config/HibernateConfig.java
- javers-spring-jpa/src/test/java/org/javers/spring/example/JaversSpringJpaApplicationConfig.java
- javers-spring/src/test/java/org/javers/spring/example/JaversSpringMongoApplicationConfig.java
Removed unnecessary use of Google Guava. Removed 1 unused import.
> Fixes #692

- javers-core/src/main/java/org/javers/core/JaversBuilder.java
- javers-core/src/main/java/org/javers/core/json/JsonConverterBuilder.java
- javers-core/src/main/java/org/javers/core/metamodel/object/GlobalIdFactory.java
- javers-core/src/main/java/org/javers/guava/MultimapTypeAdapter.java
- javers-core/src/main/java/org/javers/repository/inmemory/InMemoryRepository.java
- javers-core/src/main/java/org/javers/repository/jql/QueryCompiler.java
- javers-core/src/test/groovy/org/javers/core/cases/CaseWithAbstractValueObjectPath.groovy
- javers-core/src/test/groovy/org/javers/core/cases/NestedListsTest.groovy
- javers-core/src/test/groovy/org/javers/core/json/typeadapter/CdoSnapshotTypeAdapterTest.groovy
- javers-core/src/test/groovy/org/javers/repository/jql/QueryRunnerIntegrationTest.groovy
- javers-core/src/test/groovy/org/javers/shadow/ShadowFactoryTest.groovy
- javers-core/src/test/java/org/javers/core/cases/EntityWithNestedList.java
- javers-core/src/test/java/org/javers/core/examples/typeNames/OldEntity.java
see https://stackoverflow.com/questions/51634751/javersexception-property-not-found-property-in-derived-class-not-found-in-abstr
> javersexception-property-not-found

- javers-core/src/main/java/org/javers/common/reflection/ReflectionUtil.java
FastClasspathScannerVersion -> ClassGraph, fixes
> https://github.com/javers/javers/issues/705

- javers-core/src/main/java/org/javers/common/string/ToStringBuilder.java
- javers-core/src/main/java/org/javers/core/diff/appenders/ValueChangeAppender.java
- javers-core/src/main/java/org/javers/core/json/typeadapter/commit/CdoSnapshotTypeAdapter.java
- javers-core/src/main/java/org/javers/core/json/typeadapter/commit/GlobalIdTypeAdapter.java
- javers-core/src/main/java/org/javers/core/metamodel/object/GlobalIdFactory.java
- javers-core/src/main/java/org/javers/core/metamodel/type/EntityType.java
- javers-core/src/main/java/org/javers/core/metamodel/type/ManagedClass.java
- javers-core/src/main/java/org/javers/core/metamodel/type/PrimitiveOrValueType.java
- javers-core/src/main/java/org/javers/core/metamodel/type/TypeMapper.java
- javers-core/src/main/java/org/javers/core/metamodel/type/TypeMapperState.java
- javers-core/src/main/java/org/javers/core/metamodel/type/UnknownType.java
- javers-core/src/main/java/org/javers/repository/jql/FilterDefinition.java
- javers-core/src/test/groovy/org/javers/core/cases/Case723TypeNameNotFound.groovy
- javers-core/src/test/groovy/org/javers/core/json/builder/ChangeTestBuilder.groovy
> https://github.com/javers/javers/issues/723

- javers-core/src/main/java/org/javers/common/exception/JaversExceptionCode.java
- javers-core/src/main/java/org/javers/core/Javers.java
- javers-core/src/main/java/org/javers/core/JaversCore.java
- javers-core/src/main/java/org/javers/core/commit/CommitFactory.java
- javers-core/src/main/java/org/javers/core/diff/ObjectGraph.java
- javers-core/src/main/java/org/javers/core/snapshot/SnapshotGraphFactory.java
- javers-core/src/test/groovy/org/javers/core/cases/CaseAsyncCommit.groovy
- javers-spring-jpa/src/main/java/org/javers/spring/jpa/JaversTransactionalDecorator.java
> 593 async commit

- javers-core/src/main/java/org/javers/core/json/CdoSnapshotSerialized.java
Fixes #782. Haven't figured out how to write a proper test for this one since issue is related to exception that only happens when working with data that was committed with an older javers version. Let me know if test is needed here and if you have some ideas about how it could be written.
P.S. this is my first PR.
> Added commitDateInstant null check before parsing it

- javers-core/src/main/java/org/javers/core/metamodel/type/CustomType.java
- javers-core/src/main/java/org/javers/core/metamodel/type/TypeFactory.java
- javers-core/src/test/groovy/org/javers/core/cases/CustomPropertyComparatorWithInheritanceCase.groovy
> Fixed "error calling Constructor for CustomType" exception when CustomPropertyComparator is registered for value's parent class

- javers-persistence-sql/src/main/java/org/javers/repository/sql/JaversSqlRepository.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/Session.java
https://github.com/javers/javers/issues/801
https://github.com/javers/javers/issues/796
> fix in SQL where clause for Oracle and MS SQL

- javers-core/src/test/groovy/org/javers/core/cases/Case798RegisteringEntitiesReferingAnotherEntityAsId.groovy
> issue 798 vr-one test case

- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/SnapshotQuery.java
> #801 replace 'fasle' with '1!=1' for oracle and mssql dbs

- javers-core/src/test/groovy/org/javers/core/JaversRepositoryE2ETest.groovy
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/SnapshotQuery.java
(Query with commitId fails on Oracle)
> fix for https://github.com/javers/javers/issues/842

- javers-spring-boot-starter-mongo/README.md
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoAutoConfiguration.java
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoConfig.java
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoHelper.java
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoProperties.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoAutoConfigurationDefaultsTest.groovy
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoAutoConfigurationOverrideTest.groovy
- javers-spring-boot-starter-mongo/src/test/resources/application-javers-mongo.yml
> Fix for #694

- javers-spring-jpa/src/main/java/org/javers/spring/jpa/JaversTransactionalDecorator.java
> #775 Solving issue when can't establish connection

- build.gradle
build was failing on my machine. Explicitly adding the gradle in the list of repos fixed the issue.
> added gralde plugin portal in the list of repos.

- javers-core/src/main/java/org/javers/core/commit/CommitId.java
- javers-core/src/test/groovy/org/javers/core/commit/CommitIdTest.groovy
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepository.java
> Fix large CommitIds not fitting double

- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversSnapshotViolationTest.groovy
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/snap/ExtendedPojo.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/snap/IExtendedPojo.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/snap/ISimplePojo.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/snap/SimpleEnum.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/snap/SimplePojo.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/snap/SnapshotViolationPojoRepository.java
Dear @bartoszwalacik ,
I created a simple test case which demonstrates issue#860. This exception occurs only when mappingStyle=bean in my case and disappears in the case of mappingStyle=field. I think this is a bug.
Hope this helps.
> javers#860 snapshot violation test case

- README.md
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/Dialects.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/KeyGenerator.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/KeyGeneratorDefinition.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/Parameter.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/Sequence.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/Session.java
inlined sequence nextval for jv_snapshot inserts
> https://github.com/javers/javers/issues/877

- javers-core/src/main/java/org/javers/common/collections/Lists.java
- javers-core/src/main/java/org/javers/core/diff/appenders/ListAsSetChangeAppender.java
- javers-core/src/main/java/org/javers/core/diff/appenders/SetChangeAppender.java
- javers-core/src/test/groovy/org/javers/core/CustomPropertyComparatorE2ETest.groovy
- javers-core/src/test/groovy/org/javers/core/model/DummyAddress.groovy
simple but slow implementation (n-squared)
> https://github.com/javers/javers/issues/832

- gradle.properties
- javers-persistence-sql/build.gradle
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/FixedSchemaFactory.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/JaversSchemaManager.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/Dialects.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/KeyGeneratorDefinition.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/Sequence.java
added dockerized tests for Oracle
fixed SQL_EXCEPTION: ORA-00917: missing comma while inserting to jv_snapshot
> https://github.com/javers/javers/issues/887

- javers-core/src/test/groovy/org/javers/core/CommitIdGeneratorTest.groovy
> remove trailing blank line in test

- javers-core/src/main/java/org/javers/core/JaversBuilder.java
- javers-core/src/main/java/org/javers/core/metamodel/annotation/Entity.java
- javers-core/src/main/java/org/javers/core/metamodel/annotation/TypeName.java
- javers-core/src/main/java/org/javers/core/metamodel/annotation/ValueObject.java
- javers-core/src/main/java/org/javers/core/metamodel/type/UnknownType.java
- javers-core/src/test/groovy/org/javers/core/cases/CaseEmbeddedIdDeserializeProblem.groovy
issue https://github.com/javers/javers/issues/897
> Itisha problem deserializing embedded id by type name

- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MapKeyDotReplacer.java
- javers-persistence-mongo/src/test/groovy/org/javers/repository/mongo/cases/KeyMapDotReplacerTest.groovy
> MapDotKeyReplacer ConcurrentModificationException fix

- javers-core/src/main/java/org/javers/core/JaversBuilder.java
- javers-core/src/main/java/org/javers/core/metamodel/type/PrimitiveOrValueType.java
- javers-core/src/test/groovy/org/javers/core/cases/CaseWithZonedDateTimeComparator.groovy
https://stackoverflow.com/questions/59185469/javers-customvaluecomparator-for-zoneddatetime
> CaseWithZonedDateTimeComparator

- javers-spring/src/main/java/org/javers/spring/annotation/JaversAuditableDelete.java
- javers-spring/src/main/java/org/javers/spring/auditable/aspect/JaversCommitAdvice.java
- javers-spring/src/main/java/org/javers/spring/auditable/aspect/springdata/AbstractSpringAuditableRepositoryAspect.java
- javers-spring/src/test/groovy/org/javers/spring/auditable/integration/JaversAuditableDeleteAspectIntegrationTest.groovy
- javers-spring/src/test/groovy/org/javers/spring/repository/DummyAuditedRepository.groovy
I couldnt figure out how to get entity class except specifying it in annotation, let me know if i missed smth
> #921: Allow JaversAuditableDelete work with id

- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepository.java
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoAutoConfiguration.java
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoProperties.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterTest.groovy
- javers-spring-boot-starter-mongo/src/test/resources/application-test.yml
Extend properties to allow disabling latest snapshot cache
> Extend properties to allow disabling latest snapshot cache

- gradle.properties
- javers-core/build.gradle
- javers-persistence-mongo/build.gradle
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoAutoConfiguration.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterDefaultsTest.groovy
Updated Spring Boot dependencies and mongodb client. Fixes #982
> Resolved compatibility issues with Spring Boot 2.3.0

- javers-persistence-sql/src/main/java/org/javers/repository/sql/SqlRepositoryBuilder.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/SqlRepositoryConfiguration.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/FixedSchemaFactory.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/SchemaNameAware.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/TableNameProvider.java
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/H2SqlRepositoryE2ETest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/H2SqlRepositoryE2EWithCustomTableNames.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/JaversSqlRepositoryE2ETest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/docker/MSSqlDockerIntegrationWithCustomTableNamesTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/docker/MySqlDockerIntegrationWithCustomTableNamesTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/docker/OracleDockerIntegrationWithCustomTableNamesTest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/integration/docker/PostgresDockerIntegrationWithCustomTableNamesTest.groovy
- javers-spring-boot-starter-sql/src/main/java/org/javers/spring/boot/sql/JaversSqlAutoConfiguration.java
- javers-spring-boot-starter-sql/src/main/java/org/javers/spring/boot/sql/JaversSqlProperties.java
- javers-spring-boot-starter-sql/src/test/groovy/org/javers/spring/sql/JaversSqlAutoConfigurationDefaultPropsTest.groovy
- javers-spring-boot-starter-sql/src/test/groovy/org/javers/spring/sql/JaversSqlAutoConfigurationTest.groovy
- javers-spring-boot-starter-sql/src/test/resources/application-test.yml
Changes for supporting custom SQL table names
> Fixes #941

- javers-core/src/test/java/org/javers/core/cases/ListWithChildClassesTest.java
https://github.com/javers/javers/issues/1030
> javers.compare throw class cast exception

- javers-core/src/test/groovy/org/javers/core/json/JsonConverterDateTimeTest.groovy
> #1068 Updating test to handle timezone conversion when zone offset contains minutes.

- javers-core/src/main/java/org/javers/core/ConditionalTypesPlugin.java
- javers-core/src/main/java/org/javers/core/RegisterTypeAdaptersPlugin.java
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoAutoConfiguration.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterIntegrationTest.groovy
- javers-spring-boot-starter-sql/src/main/java/org/javers/spring/boot/sql/JaversSqlAutoConfiguration.java
- javers-spring-boot-starter-sql/src/test/groovy/org/javers/spring/sql/JaversSqlStarterIntegrationTest.groovy
> #939 allow customizing javers builder

- javers-core/src/main/java/org/javers/common/exception/JaversExceptionCode.java
- javers-spring/src/main/java/org/javers/spring/annotation/JaversAuditableConditionalDelete.java
- javers-spring/src/main/java/org/javers/spring/auditable/aspect/JaversAuditableAspect.java
- javers-spring/src/main/java/org/javers/spring/auditable/aspect/JaversCommitAdvice.java
- javers-spring/src/test/groovy/org/javers/spring/auditable/integration/JaversAuditableConditionalDeleteAspectIntegrationTest.groovy
- javers-spring/src/test/groovy/org/javers/spring/repository/DummyAuditedRepository.groovy
Add new annotation to support conditional delete methods in spring jpa repositories
Reference: #1080
> #1080 add support for conditional delete repository methods

- javers-core/src/main/java/org/javers/common/collections/WellKnownValueTypes.java
- javers-core/src/test/groovy/org/javers/core/metamodel/type/ValueTypeTest.groovy
java.util.Locale fix for java 16
> https://github.com/javers/javers/issues/1091

- javers-core/src/main/java/org/javers/repository/api/QueryParams.java
- javers-core/src/main/java/org/javers/repository/api/QueryParamsBuilder.java
- javers-core/src/main/java/org/javers/repository/inmemory/InMemoryRepository.java
- javers-core/src/main/java/org/javers/repository/jql/QueryBuilder.java
- javers-core/src/test/groovy/org/javers/core/JaversRepositoryE2ETest.groovy
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepository.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/SnapshotQuery.java
created withCommitPropertyLike method on QueryBuilder, made implementations for InMemoryRepository,MongoRepository and SnapshotQuery, and added unit tests
issue #1096
> #1096 - created withCommitPropertyLike method on QueryBuilder

- javers-core/src/main/java/org/javers/core/diff/DiffFactory.java
> https://github.com/javers/javers/issues/1130

- javers-core/src/main/java/org/javers/core/diff/custom/CustomEmptyStringComparator.java
- javers-core/src/main/java/org/javers/core/diff/custom/CustomValueComparator.java
- javers-core/src/main/java/org/javers/core/diff/custom/NullHandlingCustomValueComparator.java
- javers-core/src/main/java/org/javers/core/metamodel/type/PrimitiveOrValueType.java
- javers-core/src/test/groovy/org/javers/core/diff/appenders/NullHandlingCustomValueComparatorTest.groovy
- javers-core/src/test/java/org/javers/core/model/DummyUserWithValues.java
#1075 - [This comment](https://github.com/javers/javers/issues/1075#issuecomment-959192203) begins the outline of the approach.
> #1075 - Allow CustomValueComparators to handle nulls

- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/CollectionNameProvider.java
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepository.java
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepositoryBuilder.java
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepositoryConfiguration.java
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoSchemaManager.java
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/pico/JaversMongoModule.java
- javers-persistence-mongo/src/test/groovy/org/javers/repository/mongo/EmbeddedMongoE2EWithRepositoryBuilderTest.groovy
[#1169 Snapshots collection name should be configurable](https://github.com/javers/javers/issues/1169)
> #1169 Snapshots collection name should be configurable

- javers-spring-boot-starter-sql/src/test/java/org/javers/spring/boot/TestApplication.java
- javers-spring-boot-starter-sql/src/test/java/org/javers/spring/boot/limit/LimitTest.java
- javers-spring-boot-starter-sql/src/test/java/org/javers/spring/boot/limit/domain/LimitEntity.java
- javers-spring-boot-starter-sql/src/test/java/org/javers/spring/boot/limit/domain/LimitRangeEntity.java
- javers-spring-boot-starter-sql/src/test/java/org/javers/spring/boot/limit/domain/LimitSignatureEntity.java
- javers-spring-boot-starter-sql/src/test/java/org/javers/spring/boot/limit/repository/LimitRangeRepository.java
- javers-spring-boot-starter-sql/src/test/java/org/javers/spring/boot/limit/repository/LimitRepository.java
- javers-spring-boot-starter-sql/src/test/java/org/javers/spring/boot/limit/repository/LimitSignatureRepository.java
Error reproduced when Entities have multiple nesting levels of child Entities
> GlobalIdTypeAdapter parseValueObjectId NPE

- javers-core/src/main/java/org/javers/core/JaversBuilder.java
- javers-spring-mongo/src/main/java/org/javers/spring/mongodb/TransactionalMongoJaversBuilder.java
ensureSchema() in mongodb starter
> https://github.com/javers/javers/issues/1192

- javers-core/src/main/java/org/javers/common/collections/WellKnownValueTypes.java
- javers-core/src/test/groovy/org/javers/core/metamodel/type/ValueTypeTest.groovy
Fix for issue [1200](https://github.com/javers/javers/issues/1200)
> add ZoneRules, ZoneId, TimeZone and ZoneInfo to WellKnownValueTypes

- javers-core/src/main/java/org/javers/repository/api/QueryParamsBuilder.java
> Fix validation in QueryParamsBuilder (fixes #1183)

- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepository.java
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepositoryConfiguration.java
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepositoryConfigurationBuilder.java
- javers-persistence-mongo/src/test/groovy/org/javers/repository/mongo/MongoE2EWithSchemaEnabledTest.groovy
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoAutoConfiguration.java
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoProperties.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterDefaultsTest.groovy
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterTest.groovy
- javers-spring-boot-starter-mongo/src/test/resources/application-test.yml
from https://github.com/javers/javers/pull/1261
> Egasimov feature/issue 1260

- javers-core/src/main/java/org/javers/core/json/JsonConverterBuilder.java
- javers-core/src/test/java/org/javers/core/cases/Case1252ObjectToNumber.java
source PR https://github.com/javers/javers/pull/1280
> Issue#1252 Object to number strategy fix

- build.gradle
- javers-core/src/main/java/org/javers/common/collections/Lists.java
- javers-core/src/main/java/org/javers/core/JaversCore.java
- javers-core/src/main/java/org/javers/core/metamodel/object/CdoSnapshot.java
- javers-core/src/test/groovy/org/javers/core/JaversRepositoryE2ETest.groovy
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/CdoSnapshotFinder.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/repositories/CdoSnapshotRepository.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/repositories/GlobalIdRepository.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/PreparedStatementExecutor.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/SelectBuilder.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/Session.java
- javers-spring-jpa/src/test/groovy/org/javers/spring/jpa/MultipleTxManagersTest.groovy
https://github.com/javers/javers/issues/1213
> reducing number of calls to GlobalIdRepository.findGlobalIdPk()

- javers-core/src/main/java/org/javers/core/metamodel/scanner/ClassAnnotationsScanner.java
- javers-core/src/test/groovy/org/javers/core/cases/Case1287ValueObjectWithIgnoredProperties.groovy
source PR https://github.com/javers/javers/pull/1289
> Kirmerzlikin diff ignore properties fix

- gradle.properties
- javers-spring-boot-starter-mongo/src/main/java/org/javers/spring/boot/mongo/JaversMongoAutoConfiguration.java
- javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterTest.groovy
fix for https://github.com/javers/javers/issues/1300
> Spring Boot 3.1.0

- javers-core/src/main/java/org/javers/core/metamodel/clazz/ClientsClassDefinition.java
- javers-core/src/main/java/org/javers/core/metamodel/clazz/ClientsClassDefinitionBuilder.java
- javers-core/src/main/java/org/javers/core/metamodel/clazz/PropertiesFilter.java
- javers-core/src/main/java/org/javers/core/metamodel/type/JaversProperty.java
- javers-core/src/main/java/org/javers/core/metamodel/type/ManagedClassFactory.java
- javers-core/src/main/java/org/javers/core/metamodel/type/ManagedPropertiesFilter.java
- javers-core/src/test/groovy/org/javers/core/JaversCommitE2ETest.groovy
source PR https://github.com/javers/javers/pull/1307
> Cberes master

- javers-core/src/main/java/org/javers/core/metamodel/type/MapType.java
- javers-core/src/test/groovy/org/javers/core/JaversDiffE2ETest.groovy
- javers-core/src/test/groovy/org/javers/core/cases/Case638Lybeck.groovy
source PR https://github.com/javers/javers/pull/1292
> Rh id gh 1269 map throws illegalargumentexception

- javers-core/src/test/groovy/org/javers/core/JaversDiffE2ETest.groovy
Hi, this is a PR that includes failing tests related to #1314
> #1314 tests to reproduce invalid type mapping

- javers-core/src/main/java/org/javers/java8support/Java8TypeAdapters.java
- javers-core/src/main/java/org/javers/java8support/MonthDayTypeAdapter.java
- javers-core/src/main/java/org/javers/java8support/OffsetTimeTypeAdapter.java
- javers-core/src/main/java/org/javers/java8support/YearMonthTypeAdapter.java
- javers-core/src/test/groovy/org/javers/core/cases/CaseWithJavaTimeFields.groovy
- javers-core/src/test/groovy/org/javers/core/json/JsonConverterJava8TypesTest.groovy
- javers-core/src/test/groovy/org/javers/core/metamodel/type/ValueTypeTest.groovy
- javers-core/src/test/groovy/org/javers/java8support/Java8TypeAdaptersE2ETest.groovy
source PR https://github.com/javers/javers/pull/1342
> Added extra java.time types to Java8TypeAdapters

- javers-core/src/main/java/org/javers/common/collections/WellKnownValueTypes.java
- javers-core/src/main/java/org/javers/core/json/AbstractJsonTypeAdapter.java
- javers-core/src/main/java/org/javers/core/json/BasicStringSuperTypeAdapter.java
- javers-core/src/main/java/org/javers/core/json/JsonAdvancedTypeAdapter.java
- javers-core/src/main/java/org/javers/core/json/JsonConverterBuilder.java
- javers-core/src/main/java/org/javers/core/json/JsonTypeAdapter.java
- javers-core/src/main/java/org/javers/core/json/typeadapter/util/PathTypeAdapter.java
- javers-core/src/main/java/org/javers/core/json/typeadapter/util/UtilTypeCoreAdapters.java
- javers-core/src/test/groovy/org/javers/core/cases/OpBoxCaseClassExtractionError.groovy
- javers-core/src/test/groovy/org/javers/core/cases/PathInaccessibleObjectExceptionTest.groovy
- javers-core/src/test/groovy/org/javers/core/json/JsonConverterUtilTypesTest.groovy
fix for https://github.com/javers/javers/issues/1350
> added ValueTypeAdapter for java.nio.file.Path

- javers-core/src/main/java/org/javers/shadow/Shadow.java
- javers-core/src/main/java/org/javers/shadow/ShadowFactory.java
source PR https://github.com/javers/javers/pull/1355
> Yezhongqiang feature/add snapshot to shadow

- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepository.java
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoSchemaManager.java
source PR https://github.com/javers/javers/pull/1367
> improve mongo query performance

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- javers-core/build.gradle
- javers-core/src/main/java/org/javers/common/reflection/ReflectionUtil.java
- javers-core/src/test/groovy/org/javers/common/reflection/ReflectionUtilTest.groovy
- javers-core/src/test/groovy/org/javers/core/cases/Java21SortedMapShouldBeStillMappedToJaversMapType.groovy
- javers-persistence-mongo/build.gradle
- javers-spring/build.gradle
- settings.gradle
source PR https://github.com/javers/javers/pull/1369
> ReflectionUtil.calculateHierarchyDistance should return superinterfaces

- javers-core/src/main/java/org/javers/core/graph/EdgeBuilder.java
- javers-core/src/main/java/org/javers/core/graph/LiveNode.java
- javers-core/src/main/java/org/javers/core/graph/NodeReuser.java
- javers-core/src/main/java/org/javers/core/graph/ObjectGraphBuilder.java
- javers-core/src/test/groovy/org/javers/core/cases/CaseSharedObjectUnsetWhenUsedInCollection.groovy
- javers-core/src/test/groovy/org/javers/core/graph/ObjectGraphBuilderTest.groovy
see https://github.com/javers/javers/issues/1358
> clarkhan counterinstance case for issues/1358

- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepository.java
- javers-persistence-mongo/src/test/groovy/org/javers/repository/mongo/cases/SkipQueryTest.groovy
Source PR https://github.com/javers/javers/pull/1392
Issue https://github.com/javers/javers/issues/1391
> Antongub master

- javers-core/src/main/java/org/javers/repository/api/QueryParams.java
- javers-core/src/main/java/org/javers/repository/api/QueryParamsBuilder.java
- javers-core/src/main/java/org/javers/repository/inmemory/InMemoryRepository.java
- javers-core/src/main/java/org/javers/repository/jql/QueryBuilder.java
- javers-core/src/test/groovy/org/javers/core/JaversRepositoryE2ETest.groovy
- javers-persistence-mongo/src/main/java/org/javers/repository/mongo/MongoRepository.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/finders/SnapshotQuery.java
Source PR https://github.com/javers/javers/pull/1396/files
> Anthony in math feature/add from version and to version in query

- javers-core/src/main/java/org/javers/core/graph/LiveNode.java
- javers-core/src/test/groovy/org/javers/core/cases/Case1400ClassCastException.groovy
https://github.com/javers/javers/issues/1400
> Bartebor issue1400

- javers-persistence-sql/src/main/java/org/javers/repository/sql/schema/JaversSchemaManager.java
- javers-persistence-sql/src/main/java/org/javers/repository/sql/session/PreparedStatementExecutor.java
source PR https://github.com/javers/javers/pull/1409
> Close ResultSet instances after use

- javers-core/src/main/java/org/javers/core/JaversBuilder.java
Simple change of access modifier to public.
> 1439 Made method withCustomCommitIdGenerator public.

- javers-core/src/main/java/org/javers/core/json/typeadapter/commit/GlobalIdTypeAdapter.java
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/RefactoredClassE2ETest.groovy
- javers-persistence-sql/src/test/groovy/org/javers/repository/sql/cases/RefactoredClassE2ETest.groovy
source PR https://github.com/javers/javers/pull/1445
> #1444 Address the commit issue of the refactored class

- javers-core/src/main/java/org/javers/common/collections/Sets.java
- javers-core/src/main/java/org/javers/core/diff/GraphPair.java
- javers-core/src/test/groovy/org/javers/core/cases/Case1370GlobalIdCollisionEntityType.groovy
Hi,
Please help to review fix for #1370.
Thanks,
> Fixes #1370: Fixes GlobalID hash collission.

- javers-spring-boot-starter-mongo/build.gradle
- javers-spring-boot-starter-redis/build.gradle
- javers-spring-boot-starter-sql/build.gradle
Solution for #1458 - the configuration properties metadata are generated in the build directory
> #1458 Generate spring configuration metadata for springboot starters
